FROM alpine

RUN apk update && apk add bash

RUN mkdir /opt/app

COPY rotate_callsign_to_rds.sh /opt/app/

RUN chmod +x /opt/app/rotate_callsign_to_rds.sh

WORKDIR /opt/app

ENTRYPOINT ["/bin/bash", "/opt/app/rotate_callsign_to_rds.sh"]
